### ISSUE TITLE
missing all the twilio code?

### ISSUE THREAD

**Issue by contractorwolf** [ranman/aws-lambda-twilio-signal#1]
just watched your presentation online from signal and was having an issue integrating twilio and lambda, so i thought I could get some pointers from your code, am I missing something? does twilio not work in Lambda?

**Comment by ranman** [comment]
Heyo -- this got removed because of some concerns about my changing employers... There is another great example from an AWS employee here: https://github.com/mauerbac/lambda-gateway-twilio-demo
